"""Añadir avance_validado, validado y validador_id a Subtarea

Revision ID: b781a68d9e8a
Revises: 7af4b9267bba
Create Date: 2025-06-03 02:03:56.933976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b781a68d9e8a'
down_revision = '7af4b9267bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avance_validado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('validador_id', sa.Integer(), nullable=True))
        # Le damos un nombre al foreign key constraint:
        batch_op.create_foreign_key(
            'fk_subtarea_validador_user',   # ← nombre del constraint
            'user',
            ['validador_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtarea', schema=None) as batch_op:
        # Eliminamos el constraint usando el mismo nombre:
        batch_op.drop_constraint('fk_subtarea_validador_user', type_='foreignkey')
        batch_op.drop_column('validador_id')
        batch_op.drop_column('validado')
        batch_op.drop_column('avance_validado')
    # ### end Alembic commands ###
