"""Agregar campo documento_aporte en Subtarea

Revision ID: f1df24a198e8
Revises: b781a68d9e8a
Create Date: 2025-06-03 02:42:32.576821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1df24a198e8'
down_revision = 'b781a68d9e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_aporte', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtarea', schema=None) as batch_op:
        batch_op.drop_column('documento_aporte')

    # ### end Alembic commands ###
